default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/psf/black
    rev: '24.4.2'
    hooks:
    -   id: black
        args: [--config=pyproject.toml]

-   repo: https://github.com/pycqa/pydocstyle
    rev: '6.3.0'
    hooks:
    -   id: pydocstyle
        args: ['.', '--ignore=D400,D415,D212,D407,D413,D205,D203,D204']

-   repo: https://github.com/hadialqattan/pycln
    rev: 'v2.4.0'
    hooks:
    -   id: pycln
        args: ['.']

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        args: [--disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls]

-   repo: local
    hooks:
    -   id: gitleaks
        name: run gitleaks #added because original gitleaks gives SSL Error
        language: system
        pass_filenames: false
        entry: poetry run gitleaks detect .
    -   id: unittest
        name: run unit tests
        language: system
        pass_filenames: false
        entry: poetry run pytest


# -   repo: https://github.com/gitleaks/gitleaks
#     rev: v8.16.1
#     hooks:
#     -   id: gitleaks